// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: content_enrichment_queue.proto

package content_enrichment_queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentEnrichmentContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordID string   `protobuf:"bytes,1,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	Urls     []string `protobuf:"bytes,2,rep,name=Urls,proto3" json:"Urls,omitempty"`
}

func (x *ContentEnrichmentContract) Reset() {
	*x = ContentEnrichmentContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_content_enrichment_queue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentEnrichmentContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentEnrichmentContract) ProtoMessage() {}

func (x *ContentEnrichmentContract) ProtoReflect() protoreflect.Message {
	mi := &file_content_enrichment_queue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentEnrichmentContract.ProtoReflect.Descriptor instead.
func (*ContentEnrichmentContract) Descriptor() ([]byte, []int) {
	return file_content_enrichment_queue_proto_rawDescGZIP(), []int{0}
}

func (x *ContentEnrichmentContract) GetRecordID() string {
	if x != nil {
		return x.RecordID
	}
	return ""
}

func (x *ContentEnrichmentContract) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_content_enrichment_queue_proto protoreflect.FileDescriptor

var file_content_enrichment_queue_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x72, 0x69, 0x63, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x61, 0x6c, 0x67, 0x6f, 0x6c, 0x69, 0x61, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22,
	0x4b, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x72, 0x69, 0x63, 0x68,
	0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x72, 0x6c, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x55, 0x72, 0x6c, 0x73, 0x42, 0x54, 0x5a, 0x52,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x69, 0x6d, 0x69, 0x66,
	0x69, 0x6e, 0x69, 0x69, 0x43, 0x54, 0x4f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2d,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x65, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_content_enrichment_queue_proto_rawDescOnce sync.Once
	file_content_enrichment_queue_proto_rawDescData = file_content_enrichment_queue_proto_rawDesc
)

func file_content_enrichment_queue_proto_rawDescGZIP() []byte {
	file_content_enrichment_queue_proto_rawDescOnce.Do(func() {
		file_content_enrichment_queue_proto_rawDescData = protoimpl.X.CompressGZIP(file_content_enrichment_queue_proto_rawDescData)
	})
	return file_content_enrichment_queue_proto_rawDescData
}

var file_content_enrichment_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_content_enrichment_queue_proto_goTypes = []interface{}{
	(*ContentEnrichmentContract)(nil), // 0: algolia_queue.ContentEnrichmentContract
}
var file_content_enrichment_queue_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_content_enrichment_queue_proto_init() }
func file_content_enrichment_queue_proto_init() {
	if File_content_enrichment_queue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_content_enrichment_queue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentEnrichmentContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_content_enrichment_queue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_enrichment_queue_proto_goTypes,
		DependencyIndexes: file_content_enrichment_queue_proto_depIdxs,
		MessageInfos:      file_content_enrichment_queue_proto_msgTypes,
	}.Build()
	File_content_enrichment_queue_proto = out.File
	file_content_enrichment_queue_proto_rawDesc = nil
	file_content_enrichment_queue_proto_goTypes = nil
	file_content_enrichment_queue_proto_depIdxs = nil
}
