version: '3.6'
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - monitor-net

volumes:
  postgres:

networks:
  monitor-net:
    driver: bridge
