on: push
name: FeelGuuds Core Library
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run common core library tests
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "."
          GO111MODULE: "on"
        with:
          args: make run-tests
      - name: Setup test env. and run database tests
        working-directory: ./core/core-database
        run: make test
