name: release

on:
  pull_request:
    branches:
      - master
      - main
    types: [closed]
  push:
    branches:
      - master
      - main

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run common core library tests
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "."
          GO111MODULE: "on"
        with:
          args: make run-tests
      - name: Setup test env. and run database tests
        working-directory: ./core-database
        run: make test

  release-notes:
    needs: [checks]
    runs-on: ubuntu-latest
    env:
      working-directory: .
      cluster: ${{ secrets.CLUSTER_NAME }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: "--debug"
      - name: Query Prvate repo
        run: |
          gh api --header 'Accept: application/vnd.github.v3+json' --method GET /repos/SimifiniiCTO/core
      - uses: ./.github/actions/release-notes
      - name: Generate release notes
        run: |
          echo 'CHANGELOG' > /tmp/release.txt
          export GITHUB_TOKEN=${{ secrets.TOKEN }}
          github-release-notes -org SimifiniiCTO -repo core -since-latest-release >> /tmp/release.txt
      - name: Publish release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --release-notes=/tmp/release.txt --skip-validate --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} #${{ secrets.GITHUB_TOKEN }}

  bump-tags:
    needs: [checks, release-notes]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          WITH_V: true
